### ISSUE TITLE
好东西，从你这里入门了。但找到一点小不足，一起改改看。

### ISSUE THREAD

**Issue by ColinCLL** [zhonglimh/Gulp#2]
谢谢你这么一个详细的教程。不过我发现了一些小不足。
1.有sass但没有用到css的压缩工具
2.开发环境删除的文件不会在发布环境删除。
3.排除了min后缀的文件压缩，但同时他也不会过去复制过去发布环境，可能导致文件丢失。
4.文件重命名成min后缀会导致丢失html找不到文件。
暂时发现这么多，有空的时候大家修改一下，我也forkle 一下准备有空改改看。

**Comment by zhonglimh** [comment]
内容能够对你有所帮助我表示很高兴，针对你所说的4个问题所一下解答：
1. sass的输出格式中包含了压缩，即：`style: 'compressed'`，所以就没必要单独再加一个css压缩工具。如果需要css压缩，可以参考文中的 gulp-minify-css 插件用法。
2. 经常会删除改的话，可以使用 `clean` 任务，在编译前手动或自动清除一下指定目录内容，随后重新生成一次。
3. 实现的话很简单，有2个方法：
　1) 增加一个新的监听： `gulp.watch( [srcPath.script+'/*.min.js'] , ['concat']);`  
　2) 把js的监听指令修改成： `gulp.watch( [srcPath.script+'/*.js'] , ['script','concat']);`
　以上2个方法都实现 `.min.js` 文件合并生成到发布环境中，如不需要合并则可以删除 `concat` 任务中的 `.pipe(concat('libs.min.js'))` 指令，或根据自身需求单独写个新的方法，这就要看你怎么灵活应用了
4. html引用的文件及路径，需要根据 `dist` 目录中实际生成的为准，并不是依据 'src' 目录。

**Comment by ColinCLL** [comment]
好的  谢谢
